version: '2'
services:
  erddap:
    container_name: "bio-oracle-erddap"
    image: axiom/docker-erddap:2.23-jdk17-openjdk
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ERDDAP_MIN_MEMORY: 1G
      ERDDAP_MAX_MEMORY: 12G
    volumes:
      - "${PWD}/erddap/conf/config.sh:/usr/local/tomcat/bin/config.sh"
      - "${PWD}/erddap/conf/robots.txt:/usr/local/tomcat/webapps/ROOT/robots.txt"
      - "${PWD}/erddap/content:/usr/local/tomcat/content/erddap"
      - "${PWD}/erddap/data:/erddapData"
      - "${TMP}:/usr/local/tomcat/temp/"
      - "${DATA_DIR}:/datasets"
